ARG SHARELATEX_TAG=sharelatex/sharelatex:latest
FROM $SHARELATEX_TAG

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-minimal python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install pygments

RUN tlmgr update --self && \
    tlmgr install scheme-full

# Install system-wide fonts
WORKDIR /usr/share/fonts

COPY ${baseDir}/install_fonts.sh .

RUN apt-get update && apt-get install -y \
    fonts-firacode fonts-roboto fonts-open-sans \
    && chmod 700 install_fonts.sh \
    && ./install_fonts.sh \
    && rm install_fonts.sh
