ARG SHARELATEX_TAG=sharelatex/sharelatex:latest
FROM $SHARELATEX_TAG

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-minimal python3-pip \
    && python3 -m pip --no-cache-dir install pygments \
    && tlmgr update --self \
    && tlmgr install scheme-full \
    && rm -rf /var/lib/apt/lists/*

# Install system-wide fonts
WORKDIR /usr/share/fonts

COPY ${baseDir}/install_fonts.sh .

RUN apt-get update && apt-get install -y \
    fonts-firacode fonts-roboto fonts-open-sans \
    && rm -rf /var/lib/apt/lists/* \
    && chmod 700 install_fonts.sh \
    && ./install_fonts.sh \
    && rm install_fonts.sh
