ARG SHARELATEX_TAG=sharelatex/sharelatex:latest
FROM $SHARELATEX_TAG

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-dev python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install pygments

RUN tlmgr update --self && \
    tlmgr install scheme-full
